using System.Text;

namespace CodeGenerator;

internal abstract class Generator(GeneratorSettings settings)
{
    private GeneratorSettings Settings { get; } = settings;

    public virtual void Generate()
    {
        GenerateProperties();
        GenerateWriters();
    }

    protected string ReplaceDash(string p)
    {
        return p.Replace(oldValue: "-", newValue: "_");
    }

    protected string HandleReserved(string s)
    {
        return Settings.ReservedWords.Contains(s) ? $"@{s}" : s;
    }

    protected abstract void ToFrameworkProperty(StringBuilder sb, string t, PropertyDef p, string classType);

    protected abstract void ToClrProperty(StringBuilder sb, string t, string propertyName);

    protected virtual void ToSetProperty(StringBuilder sb, string propertyName, string pns, string name)
    {
        // TODO: if ({{propertyName}} is not null)
        sb.AppendLine(
            value: $$"""
                             if ({{propertyName}} != null)
                             {
                                 writer.WriteLine($"{{pns}}{{name}}=\"{ToSvgString({{propertyName}})}\"");
                             }
                     """);
    }

    private void GenerateProperties(TypeDef typeDef)
    {
        var sb = new StringBuilder();

        var ns = Settings.Namespace;
        var isAbstract = typeDef.IsAbstract;
        var className = ReplaceDash(p: typeDef.TargetTpe);
        var baseType = typeDef.TargetTpe == Settings.BaseWriterType
            ? Settings.ElementBaseType
            : ReplaceDash(p: typeDef.BaseType);

        // Begin Class

        sb.AppendLine(
            value: $$"""
                     // <auto-generated />
                     #nullable enable

                     namespace {{ns}};
 
                     public{{(isAbstract ? " abstract" : "")}} partial class {{HandleReserved(className)}} : {{HandleReserved(baseType)}}
                     {
                     """);

        // Svg Tag

        if (typeDef.TargetTpe == Settings.BaseWriterType)
        {
            sb.AppendLine(
                value: $$"""
                             protected abstract string SvgTag { get; }
                         """);

            if (typeDef.Properties.Length > 0)
            {
                sb.AppendLine(
                    value: $$"""

                             """);
            }
        }
        else
        {
            if (!isAbstract)
            {
                sb.AppendLine(
                    value: $$"""
                                 protected override string SvgTag => "{{typeDef.TargetTpe}}";
                             """);

                if (typeDef.Properties.Length > 0)
                {
                    sb.AppendLine(
                        value: $$"""

                                 """);
                }
            }
        }

        // Register Avalonia Properties

        for (var j = 0; j < typeDef.Properties.Length; j++)
        {
            var p = typeDef.Properties[j];
            var t = HandleReserved(ReplaceDash(p.Type));
            var classType = HandleReserved(ReplaceDash(p: typeDef.TargetTpe));

            ToFrameworkProperty(sb, t, p, classType);

            sb.AppendLine(value: "");
        }

        // CLR Properties

        for (var k = 0; k < typeDef.Properties.Length; k++)
        {
            var p = typeDef.Properties[k];
            // TODO: Handle property types
            var t = HandleReserved(ReplaceDash(p.Type));
            var propertyName = ReplaceDash(p: p.Name);

            ToClrProperty(sb, t, propertyName);

            if (k < typeDef.Properties.Length - 1)
            {
                sb.AppendLine(value: "");
            }
        }

        // End Class

        sb.AppendLine(
            value: $$"""
                     }
                     """);

        WriteFile(typeDef, Settings.BasePath, ".Properties.g.cs", sb);
    }

    private void GenerateProperties()
    {
        for (var i = 0; i < Settings.TypeDefs.Length; i++)
        {
            var typeDef = Settings.TypeDefs[i];

            GenerateProperties(typeDef);
        }
    }

    private void GenerateWriters(TypeDef typeDef)
    {
        var sb = new StringBuilder();

        var ns = Settings.Namespace;
        var isAbstract = typeDef.IsAbstract;
        var className = HandleReserved(ReplaceDash(p: typeDef.TargetTpe));

        // Begin Class

        sb.AppendLine(
            value: $$"""
                     // <auto-generated />
                     #nullable enable

                     namespace {{ns}};

                     public{{(isAbstract ? " abstract" : "")}} partial class {{className}}
                     {
                     """);

        // WriteAttributes

        // TODO: hack
        if (typeDef.TargetTpe == Settings.BaseWriterType)
        {
            sb.AppendLine(
                value: $$"""
                             protected virtual void WriteAttributes(TextWriter writer, element parent)
                             {
                         """);
        }
        else
        {
            sb.AppendLine(
                value: $$"""
                             protected override void WriteAttributes(TextWriter writer, element parent)
                             {
                                 base.WriteAttributes(writer, parent);
                         """);

            if (typeDef.Properties.Length > 0)
            {
                sb.AppendLine(
                    value: $$"""

                             """);
            }
        }

        for (var k = 0; k < typeDef.Properties.Length; k++)
        {
            var p = typeDef.Properties[k];
            var propertyName = HandleReserved(ReplaceDash(p: p.Name));
            var pns = p.Name == "href" ? "xlink:" : "";

            ToSetProperty(sb, propertyName, pns, p.Name);

            if (k < typeDef.Properties.Length - 1)
            {
                sb.AppendLine(value: "");
            }
        }

        sb.AppendLine(
            value: $$"""
                         }
                     """);

        // End Class

        sb.AppendLine(
            value: $$"""
                     }
                     """);

        WriteFile(typeDef, Settings.BasePath, ".Writer.g.cs", sb);
    }

    private void GenerateWriters()
    {
        for (var i = 0; i < Settings.TypeDefs.Length; i++)
        {
            var typeDef = Settings.TypeDefs[i];

            GenerateWriters(typeDef);
        }
    }

    private void WriteFile(TypeDef typeDef, string basePath, string ext, StringBuilder sb)
    {
        var outputPath = Path.Combine(basePath, typeDef.FilePath);

        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        var fileName = typeDef.TargetTpe + ext;
        var path = Path.Combine(outputPath, fileName);

        File.WriteAllText(path, sb.ToString());
    }

}
